サインアップ機能
shinonome-inc/backend-final-assignment-date pull request #1
Opened 2024-08-31 07:05 UTC by DateKento

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-09-09 13:25 UTC, yota33166 requested changes
よく書けていると思います！少しだけコメントしたので、修正お願いします！

2024-09-09 13:25 UTC, yota33166 commented on accounts/tests.py
> +        self.assertFalse(User.objects.filter(email=invalid_data["username"]).exists())
invalid_data["username"] を使って、ユーザーが登録されていないかを確認するために検索をかけていますが、検索対象が email になってしまっています。ユーザーネームで確認する場合は、検索条件を username に変更する必要があります
他のテストにおいても、同様にキーワード引数を変える必要のある箇所があるので、全て修正をお願いします！

2024-09-09 13:25 UTC, yota33166 commented on accounts/tests.py
> +        self.assertIn(SESSION_KEY, self.client.session)
ポストが正しくできるかどうかのテスト自体は「test_success_post」で行っているので、もう一度確認のテストを書く必要はないと思います
ここでは、"最終課題テスト項目要件"の「test_failure_post_with_duplicated_user」にかいてある項目をテストできればokです！

2024-09-10 06:27 UTC, DateKento commented on accounts/tests.py
> +        self.assertIn(SESSION_KEY, self.client.session)
@yota33166 
レビューありがとうございます。修正したので確認お願いします！

このページで受講生の確認事項にマークを付けていたのですが、反映されていないのでしょうか？

2024-09-25 14:54 UTC, h-iwasaki083 reviewed
遅くなってすみません！1点だけコメントしたのでご確認お願いします🙌

2024-09-25 14:54 UTC, h-iwasaki083 commented on tweets/tests.py
> +        response = self.client.get(self.url, {"username": "tester", "password": "testpassword"})
ここの第2引数はGETリクエストのクエリパラメータ（URLに追加されるデータ）を指定するために使われています。
今回このGETリクエストはログイン中のユーザーから送られているため、第2引数は省略することができます🙆‍♀️

2024-09-26 06:43 UTC, DateKento commented on tweets/tests.py
> +        response = self.client.get(self.url, {"username": "tester", "password": "testpassword"})
レビューありがとうございます！修正しましたので、ご確認をよろしくお願いします。

2024-09-27 02:52 UTC, h-iwasaki083 approved these changes
LGTM！
1点稚拙ながら補足説明入れたので、気が向いたら目を通してみてください🙌

2024-09-27 02:52 UTC, h-iwasaki083 commented on accounts/views.py
> +    success_url = reverse_lazy("tweets:home")  # 宣言をしないとエラー？
コメントがあるから一応補足すると、reverse_lazyはurlの逆引きにおいて遅延評価をするときに使います！遅延評価をすることによってその変数が実際に処理で必要になったときに変数の中身の評価（今回で言えばhomeViewを呼ぶurlが決定される）ため、サインアップ処理を終えてログイン処理まで終わった状態でhomeViewを呼ぶことができます◎

（疑問点の答えになってるかな？そして説明分かりにくいかも...。もし解決しなくて説明欲しかったらいつでも声かけてください！）

2024-09-27 06:35 UTC, DateKento commented on accounts/views.py
> +    success_url = reverse_lazy("tweets:home")  # 宣言をしないとエラー？
丁寧なご回答をありがとうございます！そしてごめんなさい。
実は？を付けていたのは、reverse_lazy()関数の継承させ方が書いているときによくわからなかっただけなんです。(継承というのもよくわかっていなくて、宣言と書いていました。)

reverse()関数ではだめな時にreverse_lazy()関数を使うのかな、と勝手に解釈していましたが、reverse_lazy()は遅延評価を行うんですね！githubなどでsign upした後にurlが自分のものに変更されている処理を実現したいときに使うのが、遅延評価によるurlの逆引きなんですね！tweetsもログイン処理を実装すればhomeViewを呼び出したときにurlが変わるのか楽しみです。

(解釈があっているかわかりませんが、reverse_lazyの理解は深まりました。？を気軽に付けないように気を付けます。遅延評価について、tweetsの処理を交えて説明してくださっているので、とても分かりやすかったです！)

2024-09-27 06:40 UTC, DateKento commented
二次レビュアーからLGTMをいただきましたが、書き込み権限がなく、マージができないようで、ご自身でマージを行っても大丈夫ですと許可をいただきましたので、マージできるかを試してみます。

2024-09-27 06:41 UTC, merged

2024-09-28 02:52 UTC, h-iwasaki083 commented on accounts/views.py
> +    success_url = reverse_lazy("tweets:home")  # 宣言をしないとエラー？
reverse_lazyっていう関数がどこから来ているのかな？の？ってことだったのか…！
reverse()ではだめな時に使うっていうのも合ってます！実際にurlが変わるわけではないんだけど、CreateViewの処理の中でsuccess_urlの出番は最後の方なので、そこまでの処理を踏まえてtweet:homeを呼べるか評価するっていう感じかな🤔

？つけて良いよ！疑問点が分かった方がレビューもしやすいので🙌